# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# list of build_freom: https://github.com/orgs/hassio-addons/packages?repo_name=addon-base
build_from:
  aarch64: "ghcr.io/hassio-addons/base/aarch64:stable"
  amd64: "ghcr.io/hassio-addons/base/amd64:stable"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on:nginx proxy for external app"
  org.opencontainers.image.description: "Home Assistant Add-on:nginx proxy for external app"
  org.opencontainers.image.source: "https://github.com/ezméghiányzik"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2024.11.2"
