# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-dockerfile
# list of build_freom: https://github.com/orgs/hassio-addons/packages?repo_name=addon-base
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base-python:3.13-alpine3.23"
  amd64: "ghcr.io/home-assistant/amd64-base-python:3.13-alpine3.23"
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: TimeKpr-Mngr (stable)"
  org.opencontainers.image.description: "Add-on to manage Timekpr-NeXT instances in Home Assistant."
  org.opencontainers.image.source: "https://github.com/ezméghiányzik"
  org.opencontainers.image.licenses: "Apache License 2.0"
args:
  TEMPIO_VERSION: "2024.11.2"
